# Generated by Django 4.1.1 on 2022-09-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='position',
        ),
    ]
