# Generated by Django 4.1.1 on 2022-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_players_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date_of_match',
            field=models.CharField(max_length=20),
        ),
    ]
